### ISSUE TITLE
Containers failed to create

### ISSUE THREAD

**Issue by rkbennett** [nsec/the-internet#10]
OS: Ubuntu
LXC: 1.10

When running" the-internet start input/Northsec 15" command I receive 
Failed to create container: <container name> : no root device could be found.

For each container it attempts to create

**Comment by stgraber** [comment]
Yeah, you'll need to make sure that the `internet-base` profile is functional as it's used as the profile of all routers that are created.

**Comment by rkbennett** [comment]
I can create a container with that image and exec to get a shell into it, is there another specific check I need to do to verify that?

**Comment by stgraber** [comment]
`lxc launch FINGERPINT blah -p internet-base`, if that works, then the-internet should work

**Comment by rkbennett** [comment]
Copy, that fixed it. Thanks for the help
