### ISSUE TITLE
Is 'internet-base' profile missing?

### ISSUE THREAD

**Issue by verydragon** [nsec/the-internet#7]
Hello ,

I want to learn about the bgp and routing , so this project offers a great opportunity. However , I am not able to create containers. It seems that a configuration is missing. Would you please direct me to the right path? 

**./the-internet create [path]**
[Oct  5 23:41:37.194] Importing the router image
[Oct  5 23:41:37.307] New router image imported: 
[Oct  5 23:41:37.307] Creating the containers
[Oct  5 23:41:37.320] Failed to configure container 'ctn-cto': not found
[Oct  5 23:41:37.353] Failed to create container 'bgp-ketchup01': Requested profile 'internet-base' doesn't exist
....
[Oct  5 23:41:39.652] Failed to create container 'bgp-marathon02': Requested profile 'internet-base' doesn't exist
[Oct  5 23:41:39.654] Failed to create container 'bgp-gss04': Requested profile 'internet-base' doesn't exist

**uname -a**
Linux 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**lxc info**
apiextensions: []
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  -x86_64
  -i686
  certificate: |
    -----BEGIN CERTIFICATE-----
....
    -----END CERTIFICATE-----
  certificatefingerprint: da0b9b5bf9794138e7e17f70aa3bd66b22aa6cc8222f67ffb94fc5f90e318e51
  driver: lxc
  driverversion: 2.0.4
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-38-generic
  server: lxd
  serverpid: 11294
  serverversion: 2.0.4
  storage: dir
  storageversion: ""
config: {}
public: false

**Comment by stgraber** [comment]
Indeed, it looks like we're not creating that profile when missing.

Until we do, you can fix this by first doing "lxc profile create internet-base"

**Comment by verydragon** [comment]
Thank you @stgraber . That unblocks my learning .
