### ISSUE TITLE
No longer works with lxc/lxd master 

### ISSUE THREAD

**Issue by donno** [nsec/the-internet#8]
Attempting to build the-internet as of 2016-12-28 fails with the following error.
```
nsec/the-internet/cmd_create.go:75: undefined: shared.Devices
nsec/the-internet/cmd_create.go:142: undefined: shared.Device
nsec/the-internet/cmd_create.go:151: undefined: shared.Device
nsec/the-internet/cmd_create.go:246: ct.Brief undefined (type *api.Container has no field or method Brief)
nsec/the-internet/cmd_create.go:279: ct.Brief undefined (type *api.Container has no field or method Brief)
nsec/the-internet/cmd_destroy.go:40: undefined: shared.ContainerInfo
```

I investigated if this was related to an API change in lxc/lxd so I rolled back lxd to 2.6 (by checking out the lxd-2.6 tag under my GOPATH) and sure enough it built. I retested with lxd-2.7 and it also worked.
(At the time master of github.com/lxc/lxd was 1a61f6841de9fd59f4999ae1dee768ecf4bbb775 from  dated 2016-12-23)

With some quick bisecting, it pointed me to:
> Author: @stgraber
> Date:   Wed Dec 21 18:03:46 2016 -0500
> 
>     Move Device/Devices types to lxd package
> 
>     We don't need any of their functions in the client code so move them to
>     be daemon-only and instead use generic go types in the client.

Should this be locked down to using lxd-2.7?  Or are their alternates that exist in 2.7 that would also work with lxd-'next'?

**Comment by stgraber** [comment]
I'll push an update to match the recent client changes.
